# Generated by Django 5.1.2 on 2024-10-24 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('aberto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banda', models.CharField(max_length=100)),
                ('nome_musico', models.CharField(max_length=100)),
                ('cpf_musico', models.CharField(max_length=20)),
                ('papel', models.CharField(help_text='Função ou papel do aluno na banda', max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.evento')),
            ],
        ),
    ]
