# Generated by Django 5.1.2 on 2024-10-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_musico', models.CharField(max_length=100)),
                ('cpf_musico', models.CharField(max_length=20)),
                ('papel', models.CharField(help_text='Função ou papel do aluno na banda', max_length=50)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='bands.banda')),
            ],
        ),
    ]
